---
- name: install dependency packages
  apt:
    name: "daemonize"
    state: latest


- name: setting startup command
  blockinfile: 
    path: /etc/fstab
    create: yes
    insertafter: EOF
    marker: "# {mark} startup command is /sbin/mount.rc"
    block: |
      none none rc defaults 0 0


- name: copy mount.rc
  copy: 
    src: mount.rc
    dest: /sbin/
    mode: u=rwx,g=r,o=r


- name: start systemd
  shell: |
    /sbin/mount.rc
