---
- name: Add docker GPG key
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --batch --yes --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

- name: Install basic list of packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: Add apt repository
  shell: |
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
      | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Install Docker packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Add user to docker group
  user:
    name: "{{ USER }}"
    groups: docker
    append: yes
 
#- name: Ensure docker service is enabled(WSL2)
#  shell: |
#    nsenter --target $(pidof systemd) --all systemctl enable docker
#    nsenter --target $(pidof systemd) --all systemctl start docker
